/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

#include <a_samp>

new Text:PublicTD[16];

public OnFilterScriptInit()
{
	PublicTD[0] = TextDrawCreate(609.000000, 190.000000, "ld_bum:blkdot");
	TextDrawFont(PublicTD[0], 4);
	TextDrawLetterSize(PublicTD[0], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[0], 17.000000, 118.500000);
	TextDrawSetOutline(PublicTD[0], 1);
	TextDrawSetShadow(PublicTD[0], 0);
	TextDrawAlignment(PublicTD[0], 1);
	TextDrawColor(PublicTD[0], -2686721);
	TextDrawBackgroundColor(PublicTD[0], 255);
	TextDrawBoxColor(PublicTD[0], 50);
	TextDrawUseBox(PublicTD[0], 1);
	TextDrawSetProportional(PublicTD[0], 1);
	TextDrawSetSelectable(PublicTD[0], 0);

	PublicTD[1] = TextDrawCreate(597.000000, 171.000000, "ld_beat:chit");
	TextDrawFont(PublicTD[1], 4);
	TextDrawLetterSize(PublicTD[1], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[1], 40.500000, 46.500000);
	TextDrawSetOutline(PublicTD[1], 1);
	TextDrawSetShadow(PublicTD[1], 0);
	TextDrawAlignment(PublicTD[1], 1);
	TextDrawColor(PublicTD[1], 16711935);
	TextDrawBackgroundColor(PublicTD[1], 255);
	TextDrawBoxColor(PublicTD[1], 50);
	TextDrawUseBox(PublicTD[1], 1);
	TextDrawSetProportional(PublicTD[1], 1);
	TextDrawSetSelectable(PublicTD[1], 0);

	PublicTD[2] = TextDrawCreate(599.000000, 289.000000, "ld_beat:chit");
	TextDrawFont(PublicTD[2], 4);
	TextDrawLetterSize(PublicTD[2], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[2], 40.500000, 46.500000);
	TextDrawSetOutline(PublicTD[2], 1);
	TextDrawSetShadow(PublicTD[2], 0);
	TextDrawAlignment(PublicTD[2], 1);
	TextDrawColor(PublicTD[2], -16776961);
	TextDrawBackgroundColor(PublicTD[2], 255);
	TextDrawBoxColor(PublicTD[2], 50);
	TextDrawUseBox(PublicTD[2], 1);
	TextDrawSetProportional(PublicTD[2], 1);
	TextDrawSetSelectable(PublicTD[2], 0);

	PublicTD[3] = TextDrawCreate(536.000000, 232.000000, "ld_bum:blkdot");
	TextDrawFont(PublicTD[3], 4);
	TextDrawLetterSize(PublicTD[3], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[3], 73.000000, 18.500000);
	TextDrawSetOutline(PublicTD[3], 1);
	TextDrawSetShadow(PublicTD[3], 0);
	TextDrawAlignment(PublicTD[3], 1);
	TextDrawColor(PublicTD[3], -1);
	TextDrawBackgroundColor(PublicTD[3], 255);
	TextDrawBoxColor(PublicTD[3], 50);
	TextDrawUseBox(PublicTD[3], 1);
	TextDrawSetProportional(PublicTD[3], 1);
	TextDrawSetSelectable(PublicTD[3], 0);

	PublicTD[4] = TextDrawCreate(514.000000, 218.000000, "ld_beat:chit");
	TextDrawFont(PublicTD[4], 4);
	TextDrawLetterSize(PublicTD[4], 0.600000, 2.000000);
	TextDrawTextSize(PublicTD[4], 40.500000, 46.500000);
	TextDrawSetOutline(PublicTD[4], 1);
	TextDrawSetShadow(PublicTD[4], 0);
	TextDrawAlignment(PublicTD[4], 1);
	TextDrawColor(PublicTD[4], 65535);
	TextDrawBackgroundColor(PublicTD[4], 255);
	TextDrawBoxColor(PublicTD[4], 50);
	TextDrawUseBox(PublicTD[4], 1);
	TextDrawSetProportional(PublicTD[4], 1);
	TextDrawSetSelectable(PublicTD[4], 0);

	PublicTD[5] = TextDrawCreate(555.000000, 235.000000, "ama");
	TextDrawFont(PublicTD[5], 3);
	TextDrawLetterSize(PublicTD[5], 0.266665, 1.299998);
	TextDrawTextSize(PublicTD[5], 400.000000, 17.000000);
	TextDrawSetOutline(PublicTD[5], 2);
	TextDrawSetShadow(PublicTD[5], 0);
	TextDrawAlignment(PublicTD[5], 2);
	TextDrawColor(PublicTD[5], -1);
	TextDrawBackgroundColor(PublicTD[5], 255);
	TextDrawBoxColor(PublicTD[5], 50);
	TextDrawUseBox(PublicTD[5], 0);
	TextDrawSetProportional(PublicTD[5], 1);
	TextDrawSetSelectable(PublicTD[5], 0);

	PublicTD[6] = TextDrawCreate(528.000000, 227.000000, "N");
	TextDrawFont(PublicTD[6], 2);
	TextDrawLetterSize(PublicTD[6], 0.462500, 2.849999);
	TextDrawTextSize(PublicTD[6], 400.000000, 17.000000);
	TextDrawSetOutline(PublicTD[6], 1);
	TextDrawSetShadow(PublicTD[6], 0);
	TextDrawAlignment(PublicTD[6], 1);
	TextDrawColor(PublicTD[6], -1);
	TextDrawBackgroundColor(PublicTD[6], 255);
	TextDrawBoxColor(PublicTD[6], 50);
	TextDrawUseBox(PublicTD[6], 0);
	TextDrawSetProportional(PublicTD[6], 1);
	TextDrawSetSelectable(PublicTD[6], 0);

	PublicTD[7] = TextDrawCreate(590.000000, 235.000000, "server");
	TextDrawFont(PublicTD[7], 3);
	TextDrawLetterSize(PublicTD[7], 0.266665, 1.299998);
	TextDrawTextSize(PublicTD[7], 400.000000, 17.000000);
	TextDrawSetOutline(PublicTD[7], 2);
	TextDrawSetShadow(PublicTD[7], 0);
	TextDrawAlignment(PublicTD[7], 2);
	TextDrawColor(PublicTD[7], -1);
	TextDrawBackgroundColor(PublicTD[7], 255);
	TextDrawBoxColor(PublicTD[7], 50);
	TextDrawUseBox(PublicTD[7], 0);
	TextDrawSetProportional(PublicTD[7], 1);
	TextDrawSetSelectable(PublicTD[7], 0);

	PublicTD[8] = TextDrawCreate(612.000000, 179.000000, "R");
	TextDrawFont(PublicTD[8], 2);
	TextDrawLetterSize(PublicTD[8], 0.462500, 2.849999);
	TextDrawTextSize(PublicTD[8], 400.000000, 17.000000);
	TextDrawSetOutline(PublicTD[8], 1);
	TextDrawSetShadow(PublicTD[8], 0);
	TextDrawAlignment(PublicTD[8], 1);
	TextDrawColor(PublicTD[8], -1);
	TextDrawBackgroundColor(PublicTD[8], 255);
	TextDrawBoxColor(PublicTD[8], 50);
	TextDrawUseBox(PublicTD[8], 0);
	TextDrawSetProportional(PublicTD[8], 1);
	TextDrawSetSelectable(PublicTD[8], 0);

	PublicTD[9] = TextDrawCreate(618.000000, 206.000000, "o");
	TextDrawFont(PublicTD[9], 3);
	TextDrawLetterSize(PublicTD[9], 0.483332, 1.549998);
	TextDrawTextSize(PublicTD[9], 400.000000, 17.000000);
	TextDrawSetOutline(PublicTD[9], 2);
	TextDrawSetShadow(PublicTD[9], 0);
	TextDrawAlignment(PublicTD[9], 2);
	TextDrawColor(PublicTD[9], -1);
	TextDrawBackgroundColor(PublicTD[9], 255);
	TextDrawBoxColor(PublicTD[9], 50);
	TextDrawUseBox(PublicTD[9], 0);
	TextDrawSetProportional(PublicTD[9], 1);
	TextDrawSetSelectable(PublicTD[9], 0);

	PublicTD[10] = TextDrawCreate(618.000000, 220.000000, "l");
	TextDrawFont(PublicTD[10], 3);
	TextDrawLetterSize(PublicTD[10], 0.483332, 1.549998);
	TextDrawTextSize(PublicTD[10], 400.000000, 17.000000);
	TextDrawSetOutline(PublicTD[10], 2);
	TextDrawSetShadow(PublicTD[10], 0);
	TextDrawAlignment(PublicTD[10], 2);
	TextDrawColor(PublicTD[10], -1);
	TextDrawBackgroundColor(PublicTD[10], 255);
	TextDrawBoxColor(PublicTD[10], 50);
	TextDrawUseBox(PublicTD[10], 0);
	TextDrawSetProportional(PublicTD[10], 1);
	TextDrawSetSelectable(PublicTD[10], 0);

	PublicTD[11] = TextDrawCreate(618.000000, 235.000000, "e");
	TextDrawFont(PublicTD[11], 3);
	TextDrawLetterSize(PublicTD[11], 0.483332, 1.549998);
	TextDrawTextSize(PublicTD[11], 400.000000, 17.000000);
	TextDrawSetOutline(PublicTD[11], 2);
	TextDrawSetShadow(PublicTD[11], 0);
	TextDrawAlignment(PublicTD[11], 2);
	TextDrawColor(PublicTD[11], -1);
	TextDrawBackgroundColor(PublicTD[11], 255);
	TextDrawBoxColor(PublicTD[11], 50);
	TextDrawUseBox(PublicTD[11], 0);
	TextDrawSetProportional(PublicTD[11], 1);
	TextDrawSetSelectable(PublicTD[11], 0);

	PublicTD[12] = TextDrawCreate(618.000000, 250.000000, "P");
	TextDrawFont(PublicTD[12], 3);
	TextDrawLetterSize(PublicTD[12], 0.483332, 1.549998);
	TextDrawTextSize(PublicTD[12], 400.000000, 17.000000);
	TextDrawSetOutline(PublicTD[12], 2);
	TextDrawSetShadow(PublicTD[12], 0);
	TextDrawAlignment(PublicTD[12], 2);
	TextDrawColor(PublicTD[12], -1);
	TextDrawBackgroundColor(PublicTD[12], 255);
	TextDrawBoxColor(PublicTD[12], 50);
	TextDrawUseBox(PublicTD[12], 0);
	TextDrawSetProportional(PublicTD[12], 1);
	TextDrawSetSelectable(PublicTD[12], 0);

	PublicTD[13] = TextDrawCreate(618.000000, 266.000000, "l");
	TextDrawFont(PublicTD[13], 3);
	TextDrawLetterSize(PublicTD[13], 0.483332, 1.549998);
	TextDrawTextSize(PublicTD[13], 400.000000, 17.000000);
	TextDrawSetOutline(PublicTD[13], 2);
	TextDrawSetShadow(PublicTD[13], 0);
	TextDrawAlignment(PublicTD[13], 2);
	TextDrawColor(PublicTD[13], -1);
	TextDrawBackgroundColor(PublicTD[13], 255);
	TextDrawBoxColor(PublicTD[13], 50);
	TextDrawUseBox(PublicTD[13], 0);
	TextDrawSetProportional(PublicTD[13], 1);
	TextDrawSetSelectable(PublicTD[13], 0);

	PublicTD[14] = TextDrawCreate(619.000000, 281.000000, "a");
	TextDrawFont(PublicTD[14], 3);
	TextDrawLetterSize(PublicTD[14], 0.483332, 1.549998);
	TextDrawTextSize(PublicTD[14], 400.000000, 17.000000);
	TextDrawSetOutline(PublicTD[14], 2);
	TextDrawSetShadow(PublicTD[14], 0);
	TextDrawAlignment(PublicTD[14], 2);
	TextDrawColor(PublicTD[14], -1);
	TextDrawBackgroundColor(PublicTD[14], 255);
	TextDrawBoxColor(PublicTD[14], 50);
	TextDrawUseBox(PublicTD[14], 0);
	TextDrawSetProportional(PublicTD[14], 1);
	TextDrawSetSelectable(PublicTD[14], 0);

	PublicTD[15] = TextDrawCreate(613.000000, 297.000000, "y");
	TextDrawFont(PublicTD[15], 2);
	TextDrawLetterSize(PublicTD[15], 0.462500, 2.849999);
	TextDrawTextSize(PublicTD[15], 400.000000, 17.000000);
	TextDrawSetOutline(PublicTD[15], 1);
	TextDrawSetShadow(PublicTD[15], 0);
	TextDrawAlignment(PublicTD[15], 1);
	TextDrawColor(PublicTD[15], -1);
	TextDrawBackgroundColor(PublicTD[15], 255);
	TextDrawBoxColor(PublicTD[15], 50);
	TextDrawUseBox(PublicTD[15], 0);
	TextDrawSetProportional(PublicTD[15], 1);
	TextDrawSetSelectable(PublicTD[15], 0);

	return 1;
}

public OnFilterScriptExit()
{
	TextDrawDestroy(PublicTD[0]);
	TextDrawDestroy(PublicTD[1]);
	TextDrawDestroy(PublicTD[2]);
	TextDrawDestroy(PublicTD[3]);
	TextDrawDestroy(PublicTD[4]);
	TextDrawDestroy(PublicTD[5]);
	TextDrawDestroy(PublicTD[6]);
	TextDrawDestroy(PublicTD[7]);
	TextDrawDestroy(PublicTD[8]);
	TextDrawDestroy(PublicTD[9]);
	TextDrawDestroy(PublicTD[10]);
	TextDrawDestroy(PublicTD[11]);
	TextDrawDestroy(PublicTD[12]);
	TextDrawDestroy(PublicTD[13]);
	TextDrawDestroy(PublicTD[14]);
	TextDrawDestroy(PublicTD[15]);
	return 1;
}

public OnPlayerConnect(playerid)
{
	return 1;
}

public OnPlayerDisconnect(playerid, reason)
{
	return 1;
}

public OnPlayerCommandText(playerid, cmdtext[])
{
	if(!strcmp(cmdtext, "/tdtest", true))
	{
		TextDrawShowForPlayer(playerid, PublicTD[0]);
		TextDrawShowForPlayer(playerid, PublicTD[1]);
		TextDrawShowForPlayer(playerid, PublicTD[2]);
		TextDrawShowForPlayer(playerid, PublicTD[3]);
		TextDrawShowForPlayer(playerid, PublicTD[4]);
		TextDrawShowForPlayer(playerid, PublicTD[5]);
		TextDrawShowForPlayer(playerid, PublicTD[6]);
		TextDrawShowForPlayer(playerid, PublicTD[7]);
		TextDrawShowForPlayer(playerid, PublicTD[8]);
		TextDrawShowForPlayer(playerid, PublicTD[9]);
		TextDrawShowForPlayer(playerid, PublicTD[10]);
		TextDrawShowForPlayer(playerid, PublicTD[11]);
		TextDrawShowForPlayer(playerid, PublicTD[12]);
		TextDrawShowForPlayer(playerid, PublicTD[13]);
		TextDrawShowForPlayer(playerid, PublicTD[14]);
		TextDrawShowForPlayer(playerid, PublicTD[15]);
		return 1;
	}
	return 0;
}
